/*
 * This source file was generated by the Gradle 'init' task
 */
package se.emilkronholm.pastaserver;

public class App {
    public String getGreeting() {
        return "Welcome to the pasta server!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
